baseurl: "" # the subpath of your site, e.g. /blog
cta: "https://get.zello.com/demo-zello-dispatch-hub"


excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
host: 0.0.0.0
source: _source

autoprefixer:
  only_production: true
  
sass:
  sass_dir: ./_scss
    
exclude:
  - Gemfile
  - Gemfile.lock

gems: 
  - jekyll-git_metadata
  
buttonLabel: 'Master'