# Branch deploys – any normal previewed commit
[context.branch-deploy.environment]
  command = "jekyll build && cp netlify_headers _site/_headers"
  JEKYLL_ENV = "development"
  
# PR previews
[context.deploy-preview.environment]
  command = "jekyll build && cp netlify_headers _site/_headers"
  JEKYLL_ENV = "development"

# staging.www.nkls.me
[context.staging.environment]
  command = "jekyll build && cp netlify_headers _site/_headers"
  JEKYLL_ENV = "production"
  
# content.www.nkls.me
[context.content.environment]
  command = "jekyll build && cp netlify_headers _site/_headers"
  JEKYLL_ENV = "production"

# www.nkls.me
[context.production.environment]
  command = "jekyll build"
  JEKYLL_ENV = "production"
  
# Experimental conditions. Make sure to add new experimental branches here.
[context.experiment.environment]
  command = "jekyll build"
  JEKYLL_ENV = "production"

[build]
  publish = "_site/"