[build]
  command = "jekyll build"
  publish = "_site/"
  
[context.production.environment]
  JEKYLL_ENV = production

[context.staging.environment]
  JEKYLL_ENV = production
  
# [[headers]]
#   for = "/*"
#   [context.staging]
#     Basic-Auth = "login:password"
#   [context.content]
#     Basic-Auth = "login:password"
#   [context.develop]
#     Basic-Auth = "login:password"