[build]
  command = "jekyll build"
  publish = "_site/"
  
[context.branch-deploy.environment]
  JEKYLL_ENV = "development"

[context.deploy-preview.environment]
  JEKYLL_ENV = "development"

[context.production.environment]
  JEKYLL_ENV = "production"

[context.staging.environment]
  JEKYLL_ENV = "production"
  
[context.content.environment]
  JEKYLL_ENV = "production"
  
# Make sure to set production for split testing environments  
[context.experiment.environment]
  JEKYLL_ENV = "production"
  
[[headers]]
   for = "/*"
   [context.staging]
     Basic-Auth = "login:password"
   [context.content]
     Basic-Auth = "login:password"
   [context.develop]
     Basic-Auth = "login:password"